services:
  - type: web
    name: ixodes-ricinus-interoperability
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT -w 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
